/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.23
 * Generated at: 2024-05-07 20:25:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.default_;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/default/../../../../assets/css/login.css", Long.valueOf(1715111648790L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	<link rel=\"icon\" type=\"image/x-icon\"\r\n");
      out.write("		href=\"https://scontent.fsgn2-3.fna.fbcdn.net/v/t39.30808-6/321998401_540730578207305_7283713536861378154_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeH7GR0GnV3s4pAvtEb1PP0VV88nLZnwKVVXzyctmfApVQlmsrtig1LlBfhZeJBrUVUOzvC5TjU5su2s2pPvxrU-&_nc_ohc=tk4oKJGTeJ0AX9FHgLL&_nc_ht=scontent.fsgn2-3.fna&oh=00_AfDUZFa0J85ainPL4E6ibIFONJx-v-KSwUmxEOPu69agpg&oe=6603709B\">\r\n");
      out.write("	<title>Login</title>\r\n");
      out.write("\r\n");
      out.write("	<!-- font -->\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("	<link\r\n");
      out.write("		href=\"https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\"\r\n");
      out.write("		rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("	<!-- icon -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\"\r\n");
      out.write("		integrity=\"sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==\"\r\n");
      out.write("		crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"login.css\">\r\n");
      out.write("	<style>\r\n");
      out.write("		");
      out.write("body {\n");
      out.write("	box-sizing: border-box;\n");
      out.write("	background-color: rgb(231, 231, 231);\n");
      out.write("	/* font-family: Arial, sans-serif; */\n");
      out.write("	padding: 0px;\n");
      out.write("	margin: 0px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-container {\n");
      out.write("	position: fixed;\n");
      out.write("	width: 100%;\n");
      out.write("	height: 100%;\n");
      out.write("	background-color: rgb(255, 255, 255);\n");
      out.write("	display: flex;\n");
      out.write("	align-items: center;\n");
      out.write("	justify-content: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".item1 {\n");
      out.write("	position: absolute;\n");
      out.write("	bottom: 0%;\n");
      out.write("	left: 0%;\n");
      out.write("	/* width: 30%; */\n");
      out.write("	width: 407px;\n");
      out.write("	/* height: 70%; */\n");
      out.write("	height: 457px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".item2 {\n");
      out.write("	position: absolute;\n");
      out.write("	top: 0%;\n");
      out.write("	right: 0%;\n");
      out.write("	/* width: 30%; */\n");
      out.write("	width: 407px;\n");
      out.write("	/* height: 70%; */\n");
      out.write("	height: 457px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".item3 {\n");
      out.write("	position: absolute;\n");
      out.write("	top: 85%;\n");
      out.write("	right: 23%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container {\n");
      out.write("	box-shadow: rgba(0, 0, 0, 0.15) 0px 5px 15px 0px;\n");
      out.write("	/* width: 60%; */\n");
      out.write("	/* width: 815px;\n");
      out.write("    height: 500px; */\n");
      out.write("	display: flex;\n");
      out.write("	/* flex-direction: row; */\n");
      out.write("	/* flex-wrap: wrap; */\n");
      out.write("	justify-content: center;\n");
      out.write("	background-color: rgb(255, 255, 255);\n");
      out.write("	/* margin: 80px auto; */\n");
      out.write("	position: relative;\n");
      out.write("	/* top: 50%;\n");
      out.write("    left: 50%;\n");
      out.write("    transform: translate(-50%, -50%); */\n");
      out.write("	border-radius: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".img-container {\n");
      out.write("	/* width: 47%;\n");
      out.write("    height: 100%; */\n");
      out.write("	box-shadow: rgba(0, 0, 0, 0.1) 0px 0px 5px 0px, rgba(0, 0, 0, 0.1) 0px 0px 1px 0px;\n");
      out.write("	border-radius: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".s-img {\n");
      out.write("	position: relative;\n");
      out.write("	display: flex;\n");
      out.write("	flex-direction: column;\n");
      out.write("	justify-content: center;\n");
      out.write("	height: 100%;\n");
      out.write("	width: 100%;\n");
      out.write("	align-items: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".s-img .background {\n");
      out.write("	position: relative;\n");
      out.write("	opacity: 0.25;\n");
      out.write("	border-radius: 15px;\n");
      out.write("	width: 100%;\n");
      out.write("	height: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".item4 {\n");
      out.write("	position: absolute;\n");
      out.write("	bottom: 0%;\n");
      out.write("	left: 0%;\n");
      out.write("	z-index: 2;\n");
      out.write("	opacity: 1;\n");
      out.write("	width: 27%;\n");
      out.write("	height: 35%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".item5 {\n");
      out.write("	position: absolute;\n");
      out.write("	top: 0%;\n");
      out.write("	right: 0%;\n");
      out.write("	z-index: 2;\n");
      out.write("	opacity: 1;\n");
      out.write("	width: 43%;\n");
      out.write("	height: 24%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".item6 {\n");
      out.write("	position: absolute;\n");
      out.write("	top: 40%;\n");
      out.write("	left: 30%;\n");
      out.write("	z-index: 2;\n");
      out.write("	opacity: 1;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".layoutLogin {\n");
      out.write("	position: absolute;\n");
      out.write("	width: 100%;\n");
      out.write("	height: 100%;\n");
      out.write("	background-color: rgba(148, 171, 192, 0.5);\n");
      out.write("	top: 0px;\n");
      out.write("	left: 0px;\n");
      out.write("	z-index: 1;\n");
      out.write("	border-radius: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* img {\n");
      out.write("    height: 100%;\n");
      out.write("    width: 100%;\n");
      out.write("} */\n");
      out.write("\n");
      out.write(".header {\n");
      out.write("	display: flex;\n");
      out.write("	padding-bottom: 15px;\n");
      out.write("	column-gap: 2px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-button,\n");
      out.write(".register-button {\n");
      out.write("	width: 50%;\n");
      out.write("	text-align: center;\n");
      out.write("	position: relative;\n");
      out.write("	/* padding: 8px; */\n");
      out.write("	margin: 0;\n");
      out.write("	background: none;\n");
      out.write("	color: black;\n");
      out.write("	font-size: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login,\n");
      out.write(".register,\n");
      out.write(".login1,\n");
      out.write(".register1 {\n");
      out.write("	width: 100%;\n");
      out.write("	text-align: center;\n");
      out.write("	position: relative;\n");
      out.write("	padding: 8px;\n");
      out.write("	margin: 0;\n");
      out.write("	background: none;\n");
      out.write("	color: black;\n");
      out.write("	font-size: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login:hover,\n");
      out.write(".register:hover,\n");
      out.write(".login1:hover,\n");
      out.write(".register1:hover {\n");
      out.write("	background: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".register::before {\n");
      out.write("	content: \"\";\n");
      out.write("	position: absolute;\n");
      out.write("	left: 0;\n");
      out.write("	bottom: 0;\n");
      out.write("	height: 3px;\n");
      out.write("	width: 100%;\n");
      out.write("	background: #0a89a8;\n");
      out.write("	animation: fadeInLeft 0.4s;\n");
      out.write("	animation-delay: 0;\n");
      out.write("	animation-timing-function: ease;\n");
      out.write("	animation-fill-mode: backwards;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".register1::before,\n");
      out.write(".login::before {\n");
      out.write("	content: \"\";\n");
      out.write("	position: absolute;\n");
      out.write("	bottom: 0;\n");
      out.write("	height: 3px;\n");
      out.write("	width: 0;\n");
      out.write("	background: #0a89a8;\n");
      out.write("	transition-duration: 0.4s;\n");
      out.write("	transition-timing-function: ease;\n");
      out.write("	transition-delay: 0s;\n");
      out.write("	transition-property: width;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* .register1::before {\n");
      out.write("    left: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login::before {\n");
      out.write("    right: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".register-button:hover .register1::before {\n");
      out.write("    width: 100%;\n");
      out.write("} \n");
      out.write("\n");
      out.write(".login-button:hover .login::before {\n");
      out.write("    width: 100%;\n");
      out.write("} */\n");
      out.write("\n");
      out.write(".login1::before {\n");
      out.write("	content: \"\";\n");
      out.write("	position: absolute;\n");
      out.write("	left: 0;\n");
      out.write("	bottom: 0;\n");
      out.write("	width: 100%;\n");
      out.write("	height: 3px;\n");
      out.write("	background: #0a89a8;\n");
      out.write("	animation: fadeInRight 0.4s;\n");
      out.write("	animation-delay: 0;\n");
      out.write("	animation-timing-function: ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".content-container {\n");
      out.write("	display: flex;\n");
      out.write("	align-items: center;\n");
      out.write("	justify-content: center;\n");
      out.write("	width: 53%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".content {\n");
      out.write("	width: 65%;\n");
      out.write("	display: flex;\n");
      out.write("	flex-direction: column;\n");
      out.write("	margin: 0 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".input {\n");
      out.write("	padding-top: 10px;\n");
      out.write("	width: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logout-container {\n");
      out.write("	box-shadow: rgba(0, 0, 0, 0.15) 0px 5px 15px 0px;\n");
      out.write("	max-width: fit-content;\n");
      out.write("	display: flex;\n");
      out.write("	justify-content: center;\n");
      out.write("	padding: 20px;\n");
      out.write("	margin: 80px auto;\n");
      out.write("	border-radius: 15px;\n");
      out.write("	animation-delay: 0s;\n");
      out.write("	animation-name: fadeInDown;\n");
      out.write("	animation-duration: 1s;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logout-wrap {\n");
      out.write("	display: flex;\n");
      out.write("	justify-content: center;\n");
      out.write("	align-items: center;\n");
      out.write("	flex-direction: column;\n");
      out.write("	width: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".header-content,\n");
      out.write(".header-content h2 {\n");
      out.write("	margin: 0;\n");
      out.write("	width: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".remember-me {\n");
      out.write("	display: flex;\n");
      out.write("	padding-top: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".remember-me input {\n");
      out.write("	width: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("button {\n");
      out.write("	border-radius: 25px;\n");
      out.write("	padding: 15px 42px;\n");
      out.write("	line-height: 1;\n");
      out.write("	border: none;\n");
      out.write("	background: #02b0db;\n");
      out.write("	cursor: pointer;\n");
      out.write("	font-size: 13px;\n");
      out.write("	color: #fff;\n");
      out.write("	letter-spacing: .5px;\n");
      out.write("	transition: all 0.4s 0s;\n");
      out.write("	margin-top: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("button:hover {\n");
      out.write("	background: #564DCA;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input {\n");
      out.write("	border: 1px solid rgba(210, 210, 210, 10);\n");
      out.write("	border-radius: 2px;\n");
      out.write("	width: 100%;\n");
      out.write("	letter-spacing: -0.02em;\n");
      out.write("	color: #1d1a1a;\n");
      out.write("	font-size: 15px;\n");
      out.write("	padding: 5px 10px;\n");
      out.write("	line-height: 1.5;\n");
      out.write("	margin-top: 10px;\n");
      out.write("	box-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input::placeholder {\n");
      out.write("	color: #030b1549;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input:focus {\n");
      out.write("	outline: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("* {\n");
      out.write("	font-family: \"Poppins\", sans-serif;\n");
      out.write("	font-size: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".email_error {\n");
      out.write("	opacity: 0;\n");
      out.write("	margin: 0;\n");
      out.write("	color: red;\n");
      out.write("	font-size: 14px;\n");
      out.write("	height: 20px;\n");
      out.write("	box-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".password_error {\n");
      out.write("	opacity: 0;\n");
      out.write("	margin: 0;\n");
      out.write("	color: red;\n");
      out.write("	font-size: 14px;\n");
      out.write("	height: 20px;\n");
      out.write("	box-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".active {\n");
      out.write("	opacity: 1;\n");
      out.write("	padding: 2px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".regis-form {\n");
      out.write("	display: none;\n");
      out.write("}");
      out.write("\r\n");
      out.write("	</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"login-container\">\r\n");
      out.write("		<!-- <img class=\"item1\" src=\"svgfile\\svgfile\\camcong.svg\" alt=\"\">\r\n");
      out.write("        <img class=\"item2\" src=\"svgfile\\svgfile\\bluecong.svg\" alt=\"\">\r\n");
      out.write("        <img class=\"item3\" src=\"svgfile\\svgfile\\tron.svg\" alt=\"\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"img-container\">\r\n");
      out.write("                <div class=\"s-img\">\r\n");
      out.write("                    <img class=\"background\" src=\"svgfile\\svgfile\\GroupBackground.png\" alt=\"\">\r\n");
      out.write("                    <img class=\"item4\" src=\"./svgfile\\svgfile\\Vector.png\" alt=\"\">\r\n");
      out.write("                    <img class=\"item5\" src=\"./svgfile\\svgfile\\Vector1.png\" alt=\"\">\r\n");
      out.write("                    <img class=\"item6\" src=\"./svgfile\\svgfile\\logo.svg\" alt=\"\">\r\n");
      out.write("                    <div class=\"layoutLogin\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> -->\r\n");
      out.write("\r\n");
      out.write("		<div class=\"content-container\">\r\n");
      out.write("			<div class=\"content\">\r\n");
      out.write("				<div class=\"header\">\r\n");
      out.write("					<div class=\"login-button\">\r\n");
      out.write("						<button id=\"Login\" class=\"login1\">Login</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"register-button\">\r\n");
      out.write("						<button id=\"Register\" class=\"register1\" onclick=\"regis()\">Register</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"login-form\">\r\n");
      out.write("					<div class=\"input\">\r\n");
      out.write("						<span>Email</span>\r\n");
      out.write("						<br>\r\n");
      out.write("						<input id=\"username\" type=\"text\" placeholder=\"Enter your email\">\r\n");
      out.write("						<p class=\"email_error\"></p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"password-input\">\r\n");
      out.write("						<div class=\"input\">\r\n");
      out.write("							<span>Password</span>\r\n");
      out.write("							<br>\r\n");
      out.write("							<input id=\"password\" type=\"text\" placeholder=\"Enter your password\">\r\n");
      out.write("							<p class=\"password_error\"></p>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"remember-me\">\r\n");
      out.write("						<input type=\"checkbox\" style=\"color: #00a6da; margin: 0; margin-right: 5px;\">\r\n");
      out.write("						<span>Remember me</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<button id=\"Login-button\">Login</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"regis-form\">\r\n");
      out.write("					<div class=\"input\">\r\n");
      out.write("						<span>Email</span>\r\n");
      out.write("						<br>\r\n");
      out.write("						<input id=\"username\" type=\"text\" placeholder=\"Enter your email\">\r\n");
      out.write("						<p class=\"email_error\"></p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"password-input\">\r\n");
      out.write("						<div class=\"input\">\r\n");
      out.write("							<span>Password</span>\r\n");
      out.write("							<br>\r\n");
      out.write("							<input id=\"password\" type=\"text\" placeholder=\"Enter your password\">\r\n");
      out.write("							<p class=\"password_error\"></p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"password-verify\">\r\n");
      out.write("						<div class=\"input\">\r\n");
      out.write("							<span>Confirm Your Password</span>\r\n");
      out.write("							<br>\r\n");
      out.write("							<input id=\"password\" type=\"text\" placeholder=\"Repeat your password\">\r\n");
      out.write("							<p class=\"password_error\"></p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<script src=\"<c:url value=\"/assets/js/login.js\"/>\">\r\n");
      out.write("\r\n");
      out.write("		</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
